{% set version = "2.8.3" %}

package:
  name: vsc-base
  version: {{ version }}

source:
  fn: vsc-base-{{version}}.tar.gz
  url: https://pypi.io/packages/source/v/vsc-base/vsc-base-{{ version }}.tar.gz
  sha256: 9e102ca9d94ab97c2b974c63708dab7ea4dbaa3144787f06455e16445b92f204

build:
  number: 0
  skip: True  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - vsc-install >=0.10.1
    - prospector >=0.12.1
    - pylint
    - coloredlogs
    - humanfriendly
  run:
    - coloredlogs
    - humanfriendly
    - python
    - vsc-install >=0.10.1
    - prospector >=0.12.1
    - pylint

test:
  imports:
    - vsc
    - vsc.utils

about:
  home: https://github.com/hpcugent/vsc-base
  license: LPGLv2+
  license_file: LICENSE
  summary: 'Common tools used within our organization. Originally created by the HPC team of Ghent University (http://ugent.be/hpc).'
  license_family: LGPL

extra:
  recipe-maintainers:
    - jerowe
    - boegel
