travis:
  secure:
    BINSTAR_TOKEN: 23cU2x4Q/Tx05BI6szrE5UTCOZOWTDgL7T3kRxo8F5NviIuxOa3xKPz3Zr6QdaYGdeYoDvi1MFFv5oly0TuOAGu86PzA1YrBt5BqQTHvV0GWQQebp1NmXDYeeLpHHe2mkLu2igfW1SiYFOSpSpNBA6Khs4UMTb5rptYpDnwOUyxl86P8e23zwShtvmUyYTk69oQS54wki2CeOhSvouQQAe5ByZyHR5AC7/qnSM21mWM4cM8gcUz5Pv7u4OWRkeu6EVDdL33WofU5Iqvgu7ZhgACP68xm4v10fKoOYtu9fA6MlQgcIwsEp8zIuv5YSJA+Q7Ee/mgehRNb5caXOBWKJqJIQYpZjj2N681eIO5qvQSEXSRfOuJEaYiVs1zdg+XKrHcZoM3bfbf0n2VEUO8vMlUWsAjkM5nJkLkdgzYhbJQv+J7G1k4VXD2yfFlsg+jUjfMbOftQZN1VJ6K3vzw2Jhmk11Gqzdve0yes7RaxCt6pkuISUhM8UjaI8W0X6ybvbzbC6h0XC4efxmsdGbk23kBMRQnDgqMh0LXnPn6L4mpp6pZWD5I5J5Me2acbOT87CWcblI2Rl7uM9qcxmmsaLp4tfu0LFybDmBLJLsv3zAzpzrYRmUssjNBXCaAFhwNF/OFjLZZMiKB0YrM8XiYsfXwRuVLEcGnwqifeIAsJyqU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
