travis:
  secure:
    BINSTAR_TOKEN: rOtwDFwo+aTmQaivfR90RqhdrpJhaaUPeqXchdZ+SPig9Q3qbUZL3AguyprGj6gZW3lRzJXIhihnkRJoa3T0mcU/fw2aXBs1Up+HdCwggj4VnIhu7MEy1Xuo6jRA61f6EBV1jZFkReS6YCA/bKntKxGC4ioqSKTgUNN70MgSDVB04t8NcPckIeeXth2SppAdWkQx+Vlc3SJCGX+mRIbCu/V7Y/pYn7H/SmZtZ2MBYBF53GfI7Ock6/9jnRyOQRjn3mc+3QwJv2I9dJsgS/OiTcCzpxxJ7Lej7G1uuFho+XuCOds/yKisXgH+knl08vUicJMGDBGrb+fuPitditXuUqnh+aZjyUD0P5X8pLI+jzvddljfJBdJ34HCV0lNPKSryFjzovmiKLQfTPi9F51AV+3NtQm7JaLgc+IYFnwKo1ILSOniSDfr5pecqX0I+3+5Tl0LBGWA7Xggw6Es+uErL64qihCl0oKBzDFIzz7rtO74yDc+A1mspM+QNymV4j27vae/zORljcuu9h6jxZEB3P8VjaxzQwyBVH2ecvinrJSJfDKTrbXZV5FQqKQTbTfIZeSgrVRzzqlpzZjWt2vrXlyhyMWNy7b1RlD4UcIs2SBQgUOigSjW8f5zpZhaGa5RdZNRQOviUlLjXMjsBeZMplu6j6vZdFYns8A9OAqTtn0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
